name: CI
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['develop']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          npm install
          npm run build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: npm run test

  codeclimate:
    runs-on: ubuntu-latest
    needs: [test]
    name: coverage

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v4.0.0
        with:
          coverageCommand: 'npm run test'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_REPORT }}